import { StyleSheet } from "react-native";
import { Cores } from '../../../src/styles/color';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: Cores.branco,
    height: '100vh',      
    width: '100vw',       
    padding: '12px',      
    boxSizing: 'border-box',
    fontFamily: 'sans-serif',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',   
  },
  title: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#000000',
    textAlign: 'center',
    backgroundColor: '#fff',
    padding: '4',
    borderRadius: '20px',
    marginBottom: '12px', 
    borderWidth: 2,           
  borderColor: Cores.primaria,      
  borderStyle: 'dashed',     
    flexShrink: 0,        
  },
  layoutPrincipal: {
    display: 'flex',
    flexDirection: 'row',
    gap: '16px',
    alignItems: 'stretch',
    flex: 1,              
    minHeight: 0,         
    width: '100%',
  },
  bankGrid: {
    flex: '10%',      
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gridAutoRows: '1fr',  
    gap: '8px',
    backgroundColor: '#fff',
    borderRadius: '14px',
    padding: '12px',
    borderWidth: 2,           
    borderColor: Cores.primaria,       
    borderStyle: 'dashed',     
  },
  card: {
    backgroundColor: Cores.branco,
    borderRadius: '12px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    cursor: 'grab',
    userSelect: 'none',
    touchAction: 'none',
    borderWidth: 2,          
    borderColor: Cores.primaria,      
    borderStyle: 'dashed',    
    minHeight: 0,         
  },
  cardEmoji: { fontSize: 'calc(14px + 1vw)', lineHeight: '1' }, 
  cardLabel: {
    fontSize: '10px',
    color: Cores.primaria,
    fontWeight: '600',
    textAlign: 'center',
    padding: '4px',
    lineHeight: '1.2',
  },
  zonesColumn: {
    flex: '1',            
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    justifyContent: 'space-between',
  },
  zoneRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '12px',
    flex: 1,              
    minHeight: 0,
  },
  zoneName: {
    width: '70px',
    fontSize: '14px',
    fontWeight: '700',
    color: Cores.preto,
    textAlign: 'left',
    flexShrink: 0,
  },
  dropZone: {
    flex: 1,
    height: '100%',       
    borderWidth: 2,           
    borderColor: Cores.primaria,       
    borderStyle: 'dashed',     
    borderRadius: '14px',
    backgroundColor: Cores.branco,
    display: 'flex',
    alignItems: 'center',       
    justifyContent: 'center',
    padding: '6px',
    boxSizing: 'border-box',
    overflowY: 'auto',          
  },
  dropZoneOver: {
    backgroundColor: '#d4eefa',
    borderColor: '#1A6B8A',
    borderStyle: 'solid',
  },
  dropHint: {
    fontSize: '12px',
    color: Cores.preto,
    fontStyle: 'italic',
  },
  droppedCards: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',           
    justifyContent: 'flex-start', 
    alignContent: 'flex-start', 
    width: '100%',
    padding: '4px',
  },
  droppedCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#EAF6FB',
    borderRadius: '8px',
    padding: '4px',
    width: '54px',
    cursor: 'pointer',
    border: '0.5px solid #000000',
  },
  droppedEmoji: { fontSize: '18px', lineHeight: '1' },
  droppedLabel: {
    fontSize: '8px',
    color: '#1A6B8A',
    textAlign: 'center',
    lineHeight: '1.2',
  },
  removeX: {
    fontSize: '8px',
    color: '#f66',
  },
  startBtn: {
    display: 'block',
    width: '100%',
    marginTop: '10px',
    backgroundColor: Cores.primaria,
    color: Cores.branco,
    fontWeight: '700',
    fontSize: '15px',
    padding: '12px',
    borderRadius: '30px',
    border: 'none',
    cursor: 'pointer',
    textAlign: 'center',
    flexShrink: 0,        
  },
});
